## Supervised Learning - Regression

*y* is a real number

In [ ]:
from sklearn import linear_model
'''
+--------------+
| frev         |
+--------------+
| x1 | x2 | y  |
+----+----+----+
| 2  | 3  | 4  |
+----+----+----+
| 8  | 5  | 9  |
+----+----+----+
| 6  | 4  | 7  |
+----+----+----+
| 10 | 2  | 7  |
+----+----+----+
| 4  | 2  | 4  |
+----+----+----+
| 16 | 7  | 15 |
+----+----+----+
'''
model = linear_model.LinearRegression()

#TBD: Fit/Train the model from observed data


#TBD: Use fitted/trained model to predict for any given x1, x2




## Supervised Learning - Classification
*y* is a class/category

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model.logistic import LogisticRegression
import numpy as np

'''
Building a labelled dataset of documents
'''
doc0 = "hello world"
doc1 = "foo bar"
doc2 = "lottery prize winner"
docs_train = [doc0] * 100 + [doc1] * 100 + [doc2] * 4 

docs_test = [
             "lottery winner",
             "hello foo", 
             "hello bar", 
             "lottery prize", 
             "world foo",
             "prize winner",
            ]

'''
    Converting documents to feature vectors
'''
vectorizer = CountVectorizer()
X_train = vectorizer.fit_transform(docs_train).toarray()
features = vectorizer.get_feature_names()
print(f'Features: {features}')

print(f'X_train:\n====\n{X_train}\n====\n')
Y_train = np.array([[0] * 100 + [0] * 100 + [1.0] * 4]).reshape(204,)
print(f'Y_train:\n====\n{Y_train}\n====\n')

X_test = vectorizer.transform(docs_test).toarray('F')
print(f'X_test:\n====\n{X_test}\n====\n')

'''
Choosing the model
'''
classifier = LogisticRegression()


'''
    Train the model
'''
#TBD Fit the model to training data
classifier.fit(X_train, Y_train)

'''
    Test the model
'''
#TBD Use fitted model to predict if the documents in test data are spam or not
#predictions = []
predictions = classifier.predict(X_test)

print(f'Spam classification (1 means document is spam):\n====\n{predictions}\n====\n')

Features: ['bar', 'foo', 'hello', 'lottery', 'prize', 'winner', 'world']
X_train:
====
[[0 0 1 ... 0 0 1]
 [0 0 1 ... 0 0 1]
 [0 0 1 ... 0 0 1]
 ...
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]]
====

Y_train:
====
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
====

X_test:
====
[[0 0 0 1 0 1 0]
 [0 1 1 0 0 0 0]
 [1 0 1 0 0 0 0]
 [0 0 0 1 1 0 0]
 [0 1 0 0 0 0 1]
 [0 0 0 0 1 1 0]]
====

Spam classification (1 